title: Wolf Rieder
url: "https://wolfrieder.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Jekyll Template"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "/resume.pdf"
 - name: "Publications"
   link: "/publications/"
 - name: "Service"
   link: "/service/"
 - name: "Teaching"
   link: "/teaching/"
# - name: "Students"
#   link: "students"
# - name: "Contact"
#   link: "contact"